server.port=8082

spring.datasource.url=jdbc:h2:file:./locationdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update

grpc.client.user-service.address=static://localhost:9090
grpc.client.user-service.negotiation-type=plaintext